export const quotes = [
  "El único modo de hacer un gran trabajo es amar lo que haces.",
  "La calidad no es un acto, es un hábito.",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
  "Construyendo sueños, un proyecto a la vez.",
  "La excelencia es el resultado gradual de siempre tratar de hacerlo mejor.",
  "No cuentes los días, haz que los días cuenten.",
  "La seguridad es primero, la calidad es siempre.",
  "Grandes obras se construyen con grandes equipos.",
  "La diferencia entre lo ordinario y lo extraordinario es ese pequeño extra.",
  "No busques el éxito, busca ser valioso y el éxito te seguirá.",
  "La planificación es traer el futuro al presente para que puedas hacer algo al respecto ahora.",
  "Cada ladrillo cuenta en la construcción de un legado.",
  "La arquitectura comienza donde termina la ingeniería.",
  "Trabajar duro por algo que no nos importa se llama estrés. Trabajar duro por algo que amamos se llama pasión.",
  "El camino hacia el éxito siempre está en construcción.",
  "La calidad significa hacer lo correcto cuando nadie está mirando.",
  "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos.",
  "Si puedes soñarlo, puedes construirlo.",
  "La mejor forma de predecir el futuro es creándolo.",
  "La disciplina es el puente entre metas y logros.",
  "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el valor para continuar.",
  "Cree que puedes y ya estarás a medio camino.",
  "No esperes. El momento nunca será el adecuado.",
  "Todo lo que siempre has querido está al otro lado del miedo.",
  "La oportunidad no llama a la puerta, se presenta cuando derribas la puerta.",
  "No te detengas cuando estés cansado. Detente cuando hayas terminado.",
  "El secreto para salir adelante es empezar.",
  "La única manera de hacer un gran trabajo es amar lo que haces.",
  "El éxito parece estar conectado con la acción. Las personas exitosas se mantienen en movimiento.",
  "No hay secretos para el éxito. Es el resultado de la preparación, el trabajo duro y aprender del fracaso.",
  "El futuro pertenece a quienes creen en la belleza de sus sueños.",
  "La mejor venganza es un éxito masivo.",
  "No levantes la voz, mejora tu argumento.",
  "La lógica te llevará de A a B. La imaginación te llevará a cualquier parte.",
  "Haz lo que puedas, con lo que tengas, donde estés.",
  "El hombre que mueve una montaña empieza apartando pequeñas piedras.",
  "La confianza en uno mismo es el primer secreto del éxito.",
  "El fracaso es solo la oportunidad de comenzar de nuevo de forma más inteligente.",
  "Un viaje de mil millas comienza con un solo paso.",
  "La persistencia es muy importante. No debes renunciar a menos que te veas obligado a renunciar.",
  "El riesgo viene de no saber lo que estás haciendo.",
  "El éxito es caminar de fracaso en fracaso sin perder el entusiasmo.",
  "La innovación distingue a los líderes de los seguidores.",
  "Tu tiempo es limitado, no lo desperdicies viviendo la vida de alguien más.",
  "La vida es 10% lo que te ocurre y 90% cómo reaccionas a ello.",
  "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.",
  "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.",
  "No hay atajos para cualquier lugar al que valga la pena ir.",
  "El trabajo en equipo hace que el sueño funcione.",
  "La actitud es una pequeña cosa que hace una gran diferencia.",
  "El éxito no se mide por lo que logras, sino por los obstáculos que superas.",
  "La creatividad es la inteligencia divirtiéndose.",
  "Hazlo con pasión o no lo hagas.",
  "La simplicidad es la máxima sofisticación.",
  "El conocimiento habla, pero la sabiduría escucha.",
  "No dejes que el miedo a perder sea mayor que la emoción de ganar.",
  "El único lugar donde el éxito viene antes que el trabajo es en el diccionario.",
  "La mejor preparación para mañana es hacer lo mejor que puedas hoy.",
  "Cree en ti mismo y en todo lo que eres.",
  "Sé el cambio que quieres ver en el mundo.",
  "La felicidad no es algo hecho. Proviene de tus propias acciones.",
  "Nunca es demasiado tarde para ser lo que podrías haber sido.",
  "El optimismo es la fe que conduce al logro.",
  "No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.",
  "La verdadera prueba no es si evitas el fracaso, porque no lo harás. Es si dejas que te endurezca o te avergüence.",
  "La vida es un proyecto de bricolaje.",
  "Construye tus propios sueños, o alguien más te contratará para construir los suyos.",
  "El liderazgo es la capacidad de traducir la visión en realidad.",
  "La gestión es hacer las cosas bien; el liderazgo es hacer las cosas correctas.",
  "Ninguno de nosotros es tan inteligente como todos nosotros.",
  "Juntarse es un comienzo. Seguir juntos es un progreso. Trabajar juntos es un éxito.",
  "Si quieres ir rápido, ve solo. Si quieres ir lejos, ve acompañado.",
  "El talento gana juegos, pero el trabajo en equipo gana campeonatos.",
  "Solo puedes construir un gran edificio sobre cimientos sólidos.",
  "Cada proyecto es una oportunidad para aprender algo nuevo.",
  "La seguridad no es un lema, es una forma de vida.",
  "Un trabajo bien hecho es su propia recompensa.",
  "La calidad es responsabilidad de todos.",
  "Mide dos veces, corta una vez.",
  "La precisión construye la perfección.",
  "El detalle hace la diferencia.",
  "La construcción es un arte que se habita.",
  "Construimos edificios, luego ellos nos construyen a nosotros.",
  "La arquitectura es música congelada.",
  "La ingeniería es el arte de dirigir las grandes fuentes de poder de la naturaleza para el uso y conveniencia del hombre.",
  "El cemento, el acero y el vidrio no son nada sin la visión humana.",
  "Un edificio tiene integridad al igual que un hombre.",
  "La forma sigue a la función.",
  "Menos es más.",
  "Dios está en los detalles.",
  "La casa debe ser el estuche de la vida, la máquina de felicidad.",
  "La arquitectura es el juego sabio, correcto y magnífico de los volúmenes bajo la luz.",
  "El sol no sabe lo bueno que es hasta que golpea una pared.",
  "La arquitectura despierta sentimientos en el hombre.",
  "Proporcionar arquitectura significativa no es parodiar la historia, sino articularla.",
  "La arquitectura es una forma de pensar sobre el mundo.",
  "La belleza perece en la vida, pero es inmortal en el arte.",
  "El diseño no es solo lo que se ve y se siente. El diseño es cómo funciona.",
  "Reconocer la necesidad es la condición primaria para el diseño.",
  "Todo se diseña. Pocas cosas se diseñan bien.",
  "El buen diseño es obvio. El mal diseño se nota.",
  "El diseño es inteligencia hecha visible.",
  "Piensa fuera de la caja.",
  "La creatividad requiere el coraje de dejar ir las certezas.",
  "La curiosidad es el motor del logro.",
  "Aprende de ayer, vive para hoy, espera para mañana.",
  "La educación es el arma más poderosa que puedes usar para cambiar el mundo.",
  "La mente que se abre a una nueva idea nunca volverá a su tamaño original.",
  "La inversión en conocimiento paga el mejor interés.",
  "Nunca dejes de aprender, porque la vida nunca deja de enseñar.",
  "El experto en algo fue una vez un principiante.",
  "La práctica hace al maestro.",
  "La paciencia es amarga, pero su fruto es dulce.",
  "La perseverancia es fallar 19 veces y tener éxito la vigésima.",
  "El coraje no es la ausencia de miedo, es la capacidad de actuar a pesar de él.",
  "La fuerza no viene de la capacidad física. Viene de una voluntad indomable.",
  "Lo que no te mata te hace más fuerte.",
  "Cae siete veces, levántate ocho.",
  "El dolor es temporal. La gloria es para siempre.",
  "Si estás atravesando un infierno, sigue caminando.",
  "La victoria pertenece al más perseverante.",
  "No se trata de cuántas veces te derriban, sino de cuántas veces te levantas.",
  "El carácter es lo que haces cuando nadie mira.",
  "La integridad es hacer lo correcto, incluso cuando nadie está mirando.",
  "La honestidad es el primer capítulo en el libro de la sabiduría.",
  "La confianza se gana con mil actos y se pierde con uno solo.",
  "Sé fiel a ti mismo.",
  "La gratitud convierte lo que tenemos en suficiente.",
  "Disfruta de las pequeñas cosas.",
  "La vida es corta, sonríe mientras todavía tengas dientes.",
  "La risa es la distancia más corta entre dos personas.",
  "El humor es la válvula de escape de la inteligencia.",
  "No tomes la vida demasiado en serio. Nunca saldrás vivo de ella.",
  "La felicidad es una dirección, no un lugar.",
  "El éxito es conseguir lo que quieres. La felicidad es querer lo que consigues.",
  "Haz de cada día tu obra maestra.",
  "Sé la mejor versión de ti mismo.",
  "La comparación es el ladrón de la alegría.",
  "Sé tú mismo; todos los demás ya están ocupados.",
  "La autenticidad es tu mayor activo.",
  "La humildad no es pensar menos de ti mismo, es pensar menos en ti mismo.",
  "El orgullo precede a la caída.",
  "La soberbia es la discapacidad que suele afectar a pobres infelices mortales que se encuentran de golpe con una miserable cuota de poder.",
  "Mantén tus pies en el suelo y tus ojos en las estrellas.",
  "El respeto se gana, la honestidad se aprecia, la confianza se adquiere y la lealtad se devuelve.",
  "Trata a los demás como te gustaría ser tratado.",
  "La amabilidad es un lenguaje que los sordos pueden oír y los ciegos pueden ver.",
  "Nadie se ha hecho pobre por dar.",
  "La generosidad es la inversión que nunca falla.",
  "Ayudar a otros es ayudarse a uno mismo.",
  "El servicio a los demás es el alquiler que pagas por tu habitación aquí en la tierra.",
  "La empatía es ver con los ojos de otro, escuchar con los oídos de otro y sentir con el corazón de otro.",
  "La paz comienza con una sonrisa.",
  "La violencia es el último recurso del incompetente.",
  "La libertad no es la ausencia de compromisos, sino la capacidad de escoger.",
  "El precio de la libertad es la vigilancia eterna.",
  "La justicia tardía no es justicia.",
  "La verdad os hará libres.",
  "El tiempo es el recurso más valioso.",
  "No dejes para mañana lo que puedas hacer hoy.",
  "La puntualidad es la cortesía de los reyes.",
  "El tiempo perdido nunca se recupera.",
  "Administra tu tiempo, administra tu vida.",
  "El dinero va y viene, el tiempo solo se va.",
  "La salud es la verdadera riqueza.",
  "Cuida tu cuerpo, es el único lugar que tienes para vivir.",
  "Mente sana en cuerpo sano.",
  "El descanso es parte del entrenamiento.",
  "El equilibrio es la clave.",
  "Todo en exceso es malo.",
  "La moderación en todas las cosas.",
  "La naturaleza no se apresura, y sin embargo todo se logra.",
  "Mira profundamente en la naturaleza y entonces comprenderás todo mejor.",
  "La tierra provee lo suficiente para satisfacer las necesidades de cada hombre, pero no la avaricia de cada hombre.",
  "Cuidar el medio ambiente es cuidar la vida.",
  "La sostenibilidad es el futuro.",
  "Construir verde es construir inteligente.",
  "La eficiencia energética es el primer combustible.",
  "Reciclar es dar una segunda vida.",
  "Menos residuos, más futuro.",
  "El planeta no es una herencia de nuestros padres, sino un préstamo de nuestros hijos.",
  "La tecnología es un siervo útil pero un amo peligroso.",
  "La ciencia de hoy es la tecnología del mañana.",
  "Cualquier tecnología suficientemente avanzada es indistinguible de la magia.",
  "La innovación es lo que distingue al líder de los seguidores.",
  "El progreso es imposible sin cambio.",
  "Adáptate o muere.",
  "La única constante es el cambio.",
  "El cambio es la ley de la vida.",
  "No sobreviven las especies más fuertes, ni las más inteligentes, sino las que mejor se adaptan al cambio.",
  "El futuro pertenece a quienes se preparan para él hoy.",
  "La visión sin acción es un sueño. La acción sin visión es una pesadilla.",
  "Establece metas altas y no te detengas hasta llegar allí.",
  "Apunta a la luna. Incluso si fallas, aterrizarás entre las estrellas.",
  "Si no sabes a dónde vas, cualquier camino te llevará allí.",
  "Un objetivo sin un plan es solo un deseo.",
  "Planifica tu trabajo y trabaja tu plan.",
  "El éxito es la realización progresiva de un ideal digno.",
  "La motivación es lo que te pone en marcha. El hábito es lo que hace que sigas.",
  "Somos lo que hacemos repetidamente.",
  "La excelencia no es un acto, sino un hábito.",
  "La disciplina es hacer lo que tienes que hacer, cuando tienes que hacerlo, tengas ganas o no.",
  "El autocontrol es la fuerza. El pensamiento correcto es el dominio. La calma es el poder.",
  "Domínate a ti mismo y dominarás el mundo.",
  "La fuerza de voluntad es un músculo.",
  "La procrastinación es el asesino del tiempo.",
  "Hazlo ahora. A veces 'más tarde' se convierte en 'nunca'.",
  "La acción cura el miedo.",
  "El movimiento crea emoción.",
  "No esperes a que las condiciones sean perfectas para empezar. El empezar hace que las condiciones sean perfectas.",
  "Empieza donde estás. Usa lo que tienes. Haz lo que puedas.",
  "Mejor hecho que perfecto.",
  "El perfeccionismo es el enemigo de lo bueno.",
  "Terminado es mejor que perfecto.",
  "Itera, itera, itera.",
  "Falla rápido, falla barato.",
  "Aprende de tus errores.",
  "No hay errores, solo lecciones.",
  "La experiencia es el nombre que damos a nuestros errores.",
  "El buen juicio viene de la experiencia, y la experiencia viene del mal juicio.",
  "La sabiduría es saber qué hacer a continuación; la habilidad es saber cómo hacerlo, y la virtud es hacerlo.",
  "Sé un estudiante de por vida.",
  "La lectura es a la mente lo que el ejercicio es al cuerpo.",
  "Un libro es un sueño que tienes en tus manos.",
  "El saber no ocupa lugar.",
  "Comparte tu conocimiento. Es una forma de alcanzar la inmortalidad.",
  "Enseñar es aprender dos veces.",
  "Liderar es servir.",
  "Un buen líder inspira a la gente a tener confianza en el líder; un gran líder inspira a la gente a tener confianza en sí misma.",
  "La verdadera medida del liderazgo es la influencia, nada más y nada menos.",
  "Los líderes no crean seguidores, crean más líderes."
];